schema_version = "1.0.0"

id = "animated_brush"
version = "1.0.2"
name = "Animated Texture Brush"
tagline = "Randomly cycles image sequence texture while painting"
maintainer = "Kvendy"
type = "add-on"

tags = ["Paint"]

blender_version_min = "4.4.0"

license = [
  "SPDX:GPL-3.0-or-later",
]